### PR TITLE
Some New Algorothms

### PR DESCRIPTION
**Pull request by Rasesh2005**
I Added a few new Algorithms

### CODE REVIEW

**Comment by forgotter** [comment]
Thanks for PR.  Can't merge it now since I've plans to update the project structure. 

I shall get back within a few days and would ask you to make necessary changes in code as per new structure and merge it after that. Also, please make one PR for one algorithm instead of adding all of them in single PR.

**Comment by Rasesh2005** [comment]
Ohk I didn't See its necessity so kept all files under 1 commit.But Sorry For that. I have some more algorithms in my PC and would like to add them too

**Comment by Rasesh2005** [comment]
And plz do reply in few days as i may forget ....

**Comment by Rasesh2005** [comment]
By when will u format ur project structure???

**Comment by forgotter** [comment]
Hi,
I went through your code and I'm sorry to say that this project is created with a different view. The goal is to have important algorithms and data structures which are very commonly used.

Your contribution contains code for adhoc problems and implementation such as permutation and binary search are already a part of c++ library. 

Appreciating your effort, I would suggest you to contribute your code to repository which welcomes all kind of contribution.

**Pull request closed without merging**
